USE [master]
GO
/****** Object:  Database [Tarea programada]    Script Date: 23/02/2022 10:52:52 ******/
CREATE DATABASE [Tarea programada]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tarea programada', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\Tarea programada.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Tarea programada_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\Tarea programada_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Tarea programada] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tarea programada].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Tarea programada] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Tarea programada] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Tarea programada] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Tarea programada] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Tarea programada] SET ARITHABORT OFF 
GO
ALTER DATABASE [Tarea programada] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Tarea programada] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Tarea programada] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Tarea programada] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Tarea programada] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Tarea programada] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Tarea programada] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Tarea programada] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Tarea programada] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Tarea programada] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Tarea programada] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Tarea programada] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Tarea programada] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Tarea programada] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Tarea programada] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Tarea programada] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Tarea programada] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Tarea programada] SET RECOVERY FULL 
GO
ALTER DATABASE [Tarea programada] SET  MULTI_USER 
GO
ALTER DATABASE [Tarea programada] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Tarea programada] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Tarea programada] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Tarea programada] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Tarea programada] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Tarea programada] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Tarea programada', N'ON'
GO
ALTER DATABASE [Tarea programada] SET QUERY_STORE = OFF
GO
USE [Tarea programada]
GO
/****** Object:  Table [dbo].[Articulo]    Script Date: 23/02/2022 10:52:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Articulo](
	[id] [int] NOT NULL,
	[Nombre] [nchar](128) NOT NULL,
	[Precio] [money] NOT NULL,
 CONSTRAINT [PK_Articulo] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ususario]    Script Date: 23/02/2022 10:52:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ususario](
	[id] [int] NOT NULL,
	[UserName] [nchar](16) NOT NULL,
	[Password] [nchar](16) NOT NULL,
 CONSTRAINT [PK_Ususario] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Tarea programada] SET  READ_WRITE 
GO
